# 張量說明
- 純量 | 維度: 0  | `1`
- 向量 | 維度: 1  | `[1,2,3]`
- 矩陣 | 維度: 2  | `[[1,2], [3,4]]`
- 張量 | 維度: N  | `[[[1,2], [3,4]], ... ]`

In [1]:
import tensorflow as tf
print(tf.__version__)

1.5.0


## 向量運算

In [2]:
a = tf.constant([1,2,3], name='a')
b = tf.constant([4,5,6], name='b')
c = a + b

with tf.Session() as sess:
    print('a + b = ', sess.run(c))

a + b =  [5 7 9]


## 矩陣運算

In [3]:
a = tf.constant([[1,2],[3,4]], name='a')
b = tf.constant([[1],[2]], name='b')
c = tf.matmul(a,b)

print('shape of a: ', a.shape)
print('shape of b: ', b.shape)
print('shape of c: ', c.shape)

with tf.Session() as sess:
    print('a = \n', sess.run(a))
    print('b = \n', sess.run(b))
    print('c = \n', sess.run(c))

shape of a:  (2, 2)
shape of b:  (2, 1)
shape of c:  (2, 1)
a = 
 [[1 2]
 [3 4]]
b = 
 [[1]
 [2]]
c = 
 [[ 5]
 [11]]


## 張量演算與佔位符

tf.placeholder 佔位符接收張亮，必須指定 `shape` 參數  
若張量大小尚未固定，可將 `shape` 指定為 `None`

In [3]:
import tensorflow as tf
a = tf.placeholder(shape=(None, 2), dtype=tf.int32, name='a')
with tf.Session() as sess:
    print('--代入[[1,2]]--')
    print('a = ', sess.run(a, feed_dict={a: [[1,2]]}))
    print('--代入[[1,2], [3,4]]--')
    print('a = ', sess.run(a, feed_dict={a: [[1,2], [3,4]]}))

--代入[[1,2]]--
a =  [[1 2]]
--代入[[1,2], [3,4]]--
a =  [[1 2]
 [3 4]]
