In [1]:
import tensorflow as tf
print(tf.__version__)

1.5.0


In [2]:
a = tf.constant([1,2,3], name='a')
b = tf.constant([4,5,6], name='b')
c = a + b

with tf.Session() as sess:
    print('a + b = ', sess.run(c))

a + b =  [5 7 9]


In [3]:
a = tf.constant([[1,2],[3,4]], name='a')
b = tf.constant([[1],[2]], name='b')
c = tf.matmul(a,b)

print('shape of a: ', a.shape)
print('shape of b: ', b.shape)
print('shape of c: ', c.shape)

with tf.Session() as sess:
    print('a = \n', sess.run(a))
    print('b = \n', sess.run(b))
    print('c = \n', sess.run(c))

shape of a:  (2, 2)
shape of b:  (2, 1)
shape of c:  (2, 1)
a = 
 [[1 2]
 [3 4]]
b = 
 [[1]
 [2]]
c = 
 [[ 5]
 [11]]
